os:
  - linux
  - osx
language: go
env:
  - BRANCH="master"
  - BRANCH="devel"
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libfuse-dev pkg-config fuse user-mode-linux; sudo mknod /dev/fuse c 10 229; sudo chmod 666 /dev/fuse; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install osxfuse; fi
  - git clone -b $BRANCH git://github.com/Araq/Nim.git; cd Nim; git clone -b $BRANCH --depth 1 git://github.com/nim-lang/csources; cd csources && sh build.sh; cd ..; bin/nim c koch; ./koch boot -d:release; cd ..
before_script:
  - set -e
  - set -x
  - export PATH=./Nim/bin:$PATH
  - ls -l /dev/fuse
script:
  - nim c hello
  # Travis CI doesn't support fuse.
  # Running the test on UML is a workaround but only in Linux.
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./uml_bridge.sh hello; fi
